#!/usr/bin/env bash
export LC_ALL=C
echo y | sdkmanager --licenses
pwd -L
cd /modules/devkit-core/modules/native-android/gradleops/
set -ex
new="$1"
shift
if [ $# -gt 0 ]; then
  old="$1"
  shift
else
  old='Min'
fi
old="$(echo "$old" | sed -E 's/\/$//')"
new="$(echo "$new" | sed -E 's/\/$//')"
new_lower="$(echo "$new" | tr 'A-Z' 'a-z')"
old_lower="$(echo "$old" | tr 'A-Z' 'a-z')"
cp -r "$old" "$new"
cd "$new"
cp -r ../../native-core tealeaf/src/main/jni/core
#Changing packages
package_old="com.$old_lower"
package_new="$1"
printf "printing packages \n" 
printf $package_old '\n'
printf $package_new '\n'
#Changing names
#Mac

if [ $(../ostype.sh) == "osx" ]; then
	find . -type f -print0 | xargs -0 sed -i "" "s/${package_old}/${package_new}/g"
	find . -type f -print0 | xargs -0 sed -i "" "s/${old}/${new}/g"
	find . -type f -print0 | xargs -0 sed -i "" "s/${old_lower}/${new_lower}/g"
else
#Linux
	find ./ -type f -print0 | xargs -0 sed -i  "s/${package_old}/${package_new}/g"
    find ./ -type f -print0 | xargs -0 sed -i "s/${old}/${new}/g"
    find ./ -type f -print0 | xargs -0 sed -i "s/${old_lower}/${new_lower}/g"
fi


# don't need now to rename cpp file names 
#cd tealeaf/src/main/jni/core
#for file in '*tealeaf*' ; do mv $file ${file//$old_lower/${new_lower}} ; done
#cd ../../java/com
cd app/src/main/java/com
mv "$old_lower" "$new_lower"
