#!/usr/bin/env bash
echo "Start preparing android project ..."
export JAVA_HOME=`/usr/libexec/java_home -v 1.8 `
CURJAVA=$(java -version 2>&1 >/dev/null | grep 'java version' | awk '{print $3}')
if [[ $CURJAVA == *"1.8."* ]] ; then
	echo "Using Java 1.8"
else
     echo "Java 1.8 not found, please install Java 1.8"
 	 echo "Stopping ..."
  	 exit 1
fi
export LC_ALL=C
set -ex
new="$1"
shift
if [ $# -gt 0 ]; then
  old="$1"
  shift
else
  old='Min'
fi
old="$(echo "$old" | sed -E 's/\/$//')"
new="$(echo "$new" | sed -E 's/\/$//')"
new_lower="$(echo "$new" | tr 'A-Z' 'a-z')"
old_lower="$(echo "$old" | tr 'A-Z' 'a-z')"
cp -r "$old" "$new"
cd "$new"
cp -r ../../native-core tealeaf/src/main/jni/core
#Changing packages
package_old="com.$old_lower"
package_new="$1"
printf "printing packages \n" 
printf $package_old '\n'
printf $package_new '\n'
#Changing names
#Mac
if [ $(../ostype.sh) == "osx" ]; then
	find . -type f -print0 | xargs -0 sed -i "" "s/${package_old}/${package_new}/g"
	find . -type f -print0 | xargs -0 sed -i "" "s/${old}/${new}/g"
	find . -type f -print0 | xargs -0 sed -i "" "s/${old_lower}/${new_lower}/g"
else
#Linux
	find ./ -type f -print0 | xargs -0 sed -i  "s/${package_old}/${package_new}/g"
    find ./ -type f -print0 | xargs -0 sed -i "s/${old}/${new}/g"
    find ./ -type f -print0 | xargs -0 sed -i "s/${old_lower}/${new_lower}/g"
fi
cd app/src/main/java/com
mv "$old_lower" "$new_lower"

